# Markdownlint configuration for documentation
# See: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Disable line length - code examples and URLs often exceed 80 chars
MD013: false

# Allow multiple H1 headings - design docs may have distinct major sections
MD025: false

# Allow inline HTML - needed for badges, images with styling, etc.
MD033: false

# Allow emphasis used as heading - common in docs
MD036: false

# Allow fenced code blocks without language - ASCII diagrams, plain text
MD040: false

# Allow files without top-level H1 - PR/issue templates start with H2
MD041: false
