name: Bug Report
description: Report a bug in arbitrium-core
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: Describe the bug you encountered.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install arbitrium-core with '...'
        2. Run '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: Describe what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of arbitrium-core you are using.
      placeholder: "e.g., 0.1.0"
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: The Python version you are using.
      options:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: The operating system you are using.
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: If applicable, paste any relevant log output.
      render: shell
    validations:
      required: false
