import asyncio
from typing import Any

from certamen.application.workflow.nodes.base import (
    BaseNode,
    ExecutionContext,
    NodeProperty,
    Port,
    PortType,
)
from certamen.application.workflow.registry import register_node
from certamen.shared.logging import get_contextual_logger

logger = get_contextual_logger(__name__)


@register_node
class InterrogationNode(BaseNode):
    NODE_TYPE = "tournament/interrogate"
    DISPLAY_NAME = "Adversarial Interrogation"
    CATEGORY = "Tournament"
    DESCRIPTION = (
        "Cross-examine models to extract knowledge they possess but did not share."
        " Each model interrogates others, generating pointed questions targeting"
        " gaps, weak claims, and contradictions."
    )

    INPUTS = [
        Port(
            "models",
            PortType.MODELS,
            required=True,
            description="Competing models to interrogate each other",
        ),
        Port(
            "responses",
            PortType.RESPONSES,
            required=True,
            description="Current responses from all models",
        ),
        Port(
            "question",
            PortType.STRING,
            required=True,
            description="The original question being analyzed",
        ),
    ]

    OUTPUTS = [
        Port(
            "extracted_knowledge",
            PortType.RESPONSES,
            description="Q&A pairs extracted through interrogation",
        ),
        Port(
            "questions_asked",
            PortType.RESPONSES,
            description="Questions generated by each examiner",
        ),
    ]

    PROPERTIES = {
        "max_questions_per_pair": {
            "type": "integer",
            "default": 4,
            "min": 1,
            "max": 10,
            "description": "Number of questions each model asks the other",
        },
        "rounds": {
            "type": "integer",
            "default": 1,
            "min": 1,
            "max": 3,
            "description": "Interrogation rounds",
        },
    }

    max_questions_per_pair = NodeProperty("max_questions_per_pair", int, 4)
    rounds = NodeProperty("rounds", int, 1)

    async def execute(
        self, inputs: dict[str, Any], context: ExecutionContext
    ) -> dict[str, Any]:
        from certamen.domain.interrogation.interrogator import (
            AdversarialInterrogator,
        )

        models_input = inputs.get("models")
        responses: dict[str, str] = inputs.get("responses") or {}
        question: str = inputs.get("question") or context.question

        if not responses or not question:
            return {"extracted_knowledge": {}, "questions_asked": {}}

        models_result, empty = await self.ensure_models_or_empty(models_input)
        if empty is not None:
            return {"extracted_knowledge": {}, "questions_asked": {}}
        models = models_result

        model_items = list(models.items())
        tasks = self._build_pair_tasks(model_items, responses)

        interrogator = AdversarialInterrogator(asyncio.Semaphore(4))
        max_q = self.max_questions_per_pair

        results = await asyncio.gather(
            *[
                self._interrogate_pair(
                    interrogator, *t, question=question, max_q=max_q
                )
                for t in tasks
            ],
            return_exceptions=True,
        )

        return self._collect_results(results)

    @staticmethod
    def _build_pair_tasks(
        model_items: list[tuple[str, Any]],
        responses: dict[str, str],
    ) -> list[tuple[str, str, Any, Any, str, str]]:
        tasks = []
        for i, (examiner_key, examiner_model) in enumerate(model_items):
            for j, (target_key, target_model) in enumerate(model_items):
                if i == j:
                    continue
                examiner_resp = responses.get(examiner_key, "")
                target_resp = responses.get(target_key, "")
                if not examiner_resp or not target_resp:
                    continue
                tasks.append(
                    (
                        examiner_key,
                        target_key,
                        examiner_model,
                        target_model,
                        examiner_resp,
                        target_resp,
                    )
                )
        return tasks

    @staticmethod
    async def _interrogate_pair(
        interrogator: Any,
        examiner_key: str,
        target_key: str,
        examiner_model: Any,
        target_model: Any,
        examiner_resp: str,
        target_resp: str,
        question: str,
        max_q: int,
    ) -> tuple[str, str, dict[str, str]]:
        questions = await interrogator.generate_questions(
            examiner_model=examiner_model,
            target_response=target_resp,
            other_response=examiner_resp,
            question=question,
            max_questions=max_q,
        )
        if not questions:
            return examiner_key, target_key, {}
        qa = await interrogator.conduct_interrogation(
            target_model=target_model,
            questions=questions,
            question=question,
            own_response=target_resp,
        )
        return examiner_key, target_key, qa

    @staticmethod
    def _collect_results(
        results: list[Any],
    ) -> dict[str, dict[str, str]]:
        extracted_knowledge: dict[str, str] = {}
        questions_asked: dict[str, str] = {}
        for result in results:
            if isinstance(result, BaseException):
                logger.warning("Interrogation pair failed: %s", result)
                continue
            examiner_key, target_key, qa = result  # type: ignore[misc]
            pair_label = f"{examiner_key}→{target_key}"
            if qa:
                qa_text = "\n\n".join(f"Q: {q}\nA: {a}" for q, a in qa.items())
                extracted_knowledge[pair_label] = qa_text
                questions_asked[pair_label] = "\n".join(qa.keys())
        return {
            "extracted_knowledge": extracted_knowledge,
            "questions_asked": questions_asked,
        }
